# Generated by Django 3.2.7 on 2021-09-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=36)),
                ('tail', models.CharField(max_length=12)),
                ('index', models.IntegerField(default=0)),
                ('vowel', models.CharField(max_length=1)),
            ],
        ),
    ]
